.\" Manpage for sprunge-cli.
.\" Contact morgawr@gmail.com to provide feedback.
.TH man 1 "20 March 2012" "1.0" "sprunge-cli man page"
.SH NAME
sprunge-cli \- Command line interface for http://sprunge.us
.SH SYNOPSIS
sprunge-cli [-f] <text>
.SH DESCRIPTION
sprunge-cli is a command line interface for http://sprunge.us, a website that provides pastebin-like features through command line. It is used to quickly upload pieces of code/text on the internet to share with the community.
.SH OPTIONS
The -f flag allows to give a whole file as input instead of normal text.
.SH BUGS
No known bugs.
.SH AUTHOR
Federico "Morgawr" Pareschi (morgawr@gmail.com)
